# Generated by Django 4.0.5 on 2022-06-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_usercorrespondanceaddress_useraddresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddresses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercorrespondanceaddress',
            name='user',
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercorrespondanceaddress',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
