# Generated by Django 4.0.5 on 2022-06-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_userdetails_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCorrespondanceAddress',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.useraddresses'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
