# Generated by Django 4.0.5 on 2022-06-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_delete_usercorrespondanceaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_address',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='useradd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.useraddresses'),
        ),
    ]
