# Generated by Django 4.0.5 on 2022-06-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_userdetails_useradd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='useradd',
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='useradd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.userdetails'),
        ),
    ]
